--INSERT INTO tb_account (id, username, password) VALUES (1, 'Wemerson', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (2, 'Ricardo', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (3, 'Paulo', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (4, 'Hermes', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (5, 'Wallas', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (6, 'Ivison', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (7, 'Danillo', '123456');
--INSERT INTO tb_account (id, username, password) VALUES (8, 'Marcelo', '123456');